module.exports = {
  GET_TRANSACTION_DATA_ERROR_CONTROLLER: 40145,
  PROCESS_TRANSACTION_DATA_ERROR_CONTROLLER: 40146,
  CONVERTER_REQUEST_OPTIONS_ERROR_SERVICE: 40147,
  RESPONSE_MAPPER_ERROR_SERVICE: 40148,
  PROCESS_MULTIPLE_REQUESTS_ERROR_SERVICE: 40149
};
